name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'  # Ogni giorno a mezzanotte
  workflow_dispatch:

permissions:
  contents: write  # Permette all'action di fare commit

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          SHOW_TITLE: true
          SECTION_NAME: waka
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_TOTAL: true
          LANG_COUNT: 50
          STOP_AT_OTHER: false
